### ISSUE TITLE
Bump @nextcloud/vue to v8-beta

### ISSUE THREAD

**Issue by Pytal** [nextcloud/calendar-availability-vue#117]
### Is your feature request related to a problem? Please describe.

While upgrading https://github.com/nextcloud/server to `@nextcloud/vue@8` the following error is thrown
```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @nextcloud/calendar-availability-vue@0.6.0-alpha1
npm ERR! Found: @nextcloud/vue@8.0.0-beta.1
npm ERR! node_modules/@nextcloud/vue
npm ERR!   @nextcloud/vue@"^8.0.0-beta.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @nextcloud/vue@"^6.0 || ^7.0" from @nextcloud/calendar-availability-vue@0.6.0-alpha1
npm ERR! node_modules/@nextcloud/calendar-availability-vue
npm ERR!   @nextcloud/calendar-availability-vue@"^0.6.0-alpha1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @nextcloud/vue@7.12.0
npm ERR! node_modules/@nextcloud/vue
npm ERR!   peer @nextcloud/vue@"^6.0 || ^7.0" from @nextcloud/calendar-availability-vue@0.6.0-alpha1
npm ERR!   node_modules/@nextcloud/calendar-availability-vue
npm ERR!     @nextcloud/calendar-availability-vue@"^0.6.0-alpha1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Describe the solution you'd like

Bump @nextcloud/vue to v8-beta and pre-release

**Comment by Pytal** [comment]
@st3iny @ChristophWurst is this doable?

**Comment by st3iny** [comment]
Needs to be tested but I guess that it will work without issues.

**Comment by st3iny** [comment]
There are visual regressions around the button component when mixing cal-avail-lib+vue-v8beta.1 and calendar+vue-v7. They are fixed by building both with vue v8-beta.1. I could update package.json here and then do a release. We need to update all apps making use of this lib immediately as vue v7 and v8 can't be mixed apparently.

Alternative: Manage 2 branches (main + stablex.x) but I don't think it is worth it. The overhead is unnecessary for such a small lib.

**Comment by ChristophWurst** [comment]
If we need to backport we can always create a stable branch

Drop the old nc/vue version :+1:

**Comment by st3iny** [comment]
@Pytal v2.0.0-beta.1 is live on npm. For some reasons it was tagged as latest instead of beta.

**Comment by Pytal** [comment]
> @Pytal v2.0.0-beta.1 is live on npm. For some reasons it was tagged as latest instead of beta.

Thanks! Retagged!
