### ISSUE TITLE
Before selecting a day, the width of the table is super super short

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/calendar-availability-vue#5]
Before selecting a +:
<img width="268" alt="Screenshot_20211119_112827" src="https://user-images.githubusercontent.com/551757/142608329-ddec540a-b702-4c98-9aed-5ef7780e91a8.png">
after:
<img width="478" alt="Screenshot_20211119_113237" src="https://user-images.githubusercontent.com/551757/142608380-0597285d-0336-481b-9fcb-5bcc5672614d.png">

**Comment by st3iny** [comment]
Is already fixed.
